# Change these first
owner: mrlynn # Your GitHub organization or username, where this repository lives
repo: netpad-status # The name of this repository

sites:
  - name: NetPad App
    url: https://www.netpad.io
  - name: NetPad API
    url: https://netpad.io/api/v1/health
    expectedStatusCodes:
      - 200

status-website:
  cname: status.netpad.io
  name: NetPad Status
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
